/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AlarmDispatchDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "AlarmDispatchQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "AllowedRecipients": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EvaluatorFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "IngestFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "KapsoApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "KapsoPhoneNumberId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "KapsoReminderTemplate": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "KapsoWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MediaBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "NoteProcessingDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "NoteProcessingQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "NotifierFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "OpenAiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OpsAlerts": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "OpsEmails": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OutboxFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ProcessorFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "WatcherApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "WatcherBus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "WatcherTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}

import "sst"
export {}