/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "IngestFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "KapsoWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MediaBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "WatcherApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "WatcherTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}

import "sst"
export {}